export enum BodyPart {
  HEAD_NECK = 'HEAD_NECK',
  LEFT_SHOULDER = 'LEFT_SHOULDER',
  RIGHT_SHOULDER = 'RIGHT_SHOULDER',
  UPPER_BACK = 'UPPER_BACK',
  LOWER_BACK = 'LOWER_BACK',
  LEFT_ELBOW = 'LEFT_ELBOW',
  RIGHT_ELBOW = 'RIGHT_ELBOW',
  LEFT_WRIST_HAND = 'LEFT_WRIST_HAND',
  RIGHT_WRIST_HAND = 'RIGHT_WRIST_HAND',
  CHEST = 'CHEST',
  ABDOMEN = 'ABDOMEN',
  LEFT_HIP = 'LEFT_HIP',
  RIGHT_HIP = 'RIGHT_HIP',
  LEFT_KNEE = 'LEFT_KNEE',
  RIGHT_KNEE = 'RIGHT_KNEE',
  LEFT_ANKLE_FOOT = 'LEFT_ANKLE_FOOT',
  RIGHT_ANKLE_FOOT = 'RIGHT_ANKLE_FOOT',
}

export const BODY_PART_LABELS: Record<BodyPart, string> = {
  [BodyPart.HEAD_NECK]: 'Head & Neck',
  [BodyPart.LEFT_SHOULDER]: 'Left Shoulder',
  [BodyPart.RIGHT_SHOULDER]: 'Right Shoulder',
  [BodyPart.UPPER_BACK]: 'Upper Back',
  [BodyPart.LOWER_BACK]: 'Lower Back',
  [BodyPart.LEFT_ELBOW]: 'Left Elbow',
  [BodyPart.RIGHT_ELBOW]: 'Right Elbow',
  [BodyPart.LEFT_WRIST_HAND]: 'Left Wrist & Hand',
  [BodyPart.RIGHT_WRIST_HAND]: 'Right Wrist & Hand',
  [BodyPart.CHEST]: 'Chest',
  [BodyPart.ABDOMEN]: 'Abdomen',
  [BodyPart.LEFT_HIP]: 'Left Hip',
  [BodyPart.RIGHT_HIP]: 'Right Hip',
  [BodyPart.LEFT_KNEE]: 'Left Knee',
  [BodyPart.RIGHT_KNEE]: 'Right Knee',
  [BodyPart.LEFT_ANKLE_FOOT]: 'Left Ankle & Foot',
  [BodyPart.RIGHT_ANKLE_FOOT]: 'Right Ankle & Foot',
};
